### ISSUE TITLE
Paper addresses

### ISSUE THREAD

**Issue by S201961152** [CASIA-IVA-Lab/TDKD#3]
Hello，I want to refer your paper，but， I can't find the paper addresses, can you please provide it? thank you very much

**Comment by zxDeepDiver** [comment]
Hi, thanks for your attention on our  work.
This is the link of the paper:
https://dl.acm.org/doi/pdf/10.1145/3394171.3414069

You can also find it on researchgate.
https://www.researchgate.net/publication/346172975_Task_Decoupled_Knowledge_Distillation_For_Lightweight_Face_Detectors
