### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'to

### ISSUE THREAD

**Issue by S201961152** [CASIA-IVA-Lab/TDKD#7]
Hello, when I ran the detect.py, "AttributeError: 'tuple' object has no attribute 'to'", occurred, and I didn't find the cause, how can I solve it?

**Comment by zxDeepDiver** [comment]
Hi, https://github.com/CASIA-IVA-Lab/TDKD/commit/f953fd16b77540256816189edbbebf8d929e947b  

we fixed this issue.

**Comment by S201961152** [comment]
thank you!
